(define (problem farmer)
	(:domain farmer)
	
	(:init (and 
        (or (K (or (not(ri)) (si)))
		    (K (or (not(wi)) (si)))
		)
	    (K (and (fl)
		        (or (not(ri)) (and (re) (rl)))
				(or (not(si)) (and (sa) (sl)))
				(or (not(wi)) (and (wa) (wl)))
			) 
		)
		(DK (d))
		(DK (not (d)))

		)
	)
	
	(:goal (or (K (or (not(ri)) (not(si)) (and (re) (rl) (sa) (sl))))
	           (K (or (not(si)) (not(wi)) (and (sa) (sl) (wa) (wl))))
			   (K (or (not(ri)) (not(si)) (not(wi)) (and (re) (rl) (sa) (sl) (wa) (wl))))
			)
	)
)
